export const Users = [
    {
      id:1,
      profilePicture: "userimg1.jpg",
      username: "Arshad",
    },
    {
      id:2,
      profilePicture: "userimg1.jpg",
      username: "Izzy isha",
    },
    {
      id:3,
      profilePicture: "userimg1.jpg",
      username: "sazna hadhy",
    },
    {
      id:4,
      profilePicture: "userimg1.jpg",
      username: "Fazil donz",
    },
    {
      id:5,
      profilePicture: "userimg1.jpg",
      username: "Hansa Zainab",
    },
    {
      id:6,
      profilePicture: "userimg1.jpg",
      username: "Firdha Shiya",
    },
    {
      id:7,
      profilePicture: "userimg1.jpg",
      username: "Arun kumar",
    },
    {
      id:8,
      profilePicture: "userimg1.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "userimg1.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "userimg1.jpg",
      username: "Mark shamly",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post1.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "userimg1.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "userimg1.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "userimg1.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];